#Marco Boretto <marco.boretto@cern.ch> 2019
---
- name: Open port 9001 on firewalld for supervisor web/XML-RPC Interface
  firewalld:
    zone: public
    port: 9001/tcp
    permanent: true
    state: enabled
  notify:
    - restart firewalld
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install supervisor Centos
  yum:
    name: supervisor
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Copy supervisor gui configuration file
  copy:
    src: etc/supervisord.d/web-gui.ini
    dest: /etc/supervisord.d/
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Enabling supervisor service
  systemd:
    name: supervisord
    enabled: yes
    daemon_reload: yes
  notify:
    - restart supervisord

- name: Create /log folder
  file:
    path: /log
    state: directory
