---
- hosts: localhost
  remote_user: "{{ lookup('env','LOGNAME') }}"
  become: yes
  become_method: sudo
  roles:
    - { role: lib-centos, when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' }
    - firewall
    - twiddler
    - devel
    - openhpc
    - cvmfs
    - control-deps
    - externals
